//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.08 at 07:15:45 ÏÂÎç CST 
//


package org.azolla.open.common.cfg.test;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}testRefElementNode" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="testAttrbuteNode1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="testAttrbuteNode2" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testRefElementNode"
})
@XmlRootElement(name = "testRootNode")
public class TestRootNode {

    protected List<TestRefElementNode> testRefElementNode;
    @XmlAttribute
    protected String testAttrbuteNode1;
    @XmlAttribute
    protected Integer testAttrbuteNode2;

    /**
     * Gets the value of the testRefElementNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testRefElementNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestRefElementNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestRefElementNode }
     * 
     * 
     */
    public List<TestRefElementNode> getTestRefElementNode() {
        if (testRefElementNode == null) {
            testRefElementNode = new ArrayList<TestRefElementNode>();
        }
        return this.testRefElementNode;
    }

    /**
     * Gets the value of the testAttrbuteNode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestAttrbuteNode1() {
        return testAttrbuteNode1;
    }

    /**
     * Sets the value of the testAttrbuteNode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestAttrbuteNode1(String value) {
        this.testAttrbuteNode1 = value;
    }

    /**
     * Gets the value of the testAttrbuteNode2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTestAttrbuteNode2() {
        if (testAttrbuteNode2 == null) {
            return  0;
        } else {
            return testAttrbuteNode2;
        }
    }

    /**
     * Sets the value of the testAttrbuteNode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestAttrbuteNode2(Integer value) {
        this.testAttrbuteNode2 = value;
    }

}
